name: flutter_infra
description: "A new Flutter package for implementing infrastructure that almost all apps need"
version: 0.0.1
homepage: none

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
