name: flutter_infra
description: A comprehensive Flutter package providing clean, type-safe local storage solutions and robust network infrastructure with advanced token management and refresh strategies.
version: 0.0.1
homepage: https://github.com/your-username/flutter_infra
repository: https://github.com/your-username/flutter_infra
issue_tracker: https://github.com/your-username/flutter_infra/issues
documentation: https://github.com/your-username/flutter_infra/tree/main/doc

topics:
  - flutter
  - storage
  - network
  - http
  - secure-storage

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  http: ^1.2.0
  dio: ^5.7.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
